"use client";

import { useState, useRef, useEffect } from "react";
import AIToolLayout from "@/components/AIToolLayout";
import Link from "next/link";
import { trackUsage } from "@/lib/tracker";
import pricingData from "@/lib/llmPricing.json";

export default function LLMCostCalculator() {
    const [modelSlug, setModelSlug] = useState("gpt-4o-mini");
    const [inputTokens, setInputTokens] = useState(1000);
    const [outputTokens, setOutputTokens] = useState(500);
    const [requestsPerDay, setRequestsPerDay] = useState(1000);
    
    const tracked = useRef(false);

    useEffect(() => {
        if (!tracked.current) {
            trackUsage("llm-cost-calculator");
            tracked.current = true;
        }
    }, []);

    // Get current model metadata
    const currentModel = pricingData.find(m => m.slug === modelSlug) || pricingData[1];

    // Core Calculations
    const costPerRequest = (inputTokens / 1_000_000) * currentModel.inputCostPerM + 
                            (outputTokens / 1_000_000) * currentModel.outputCostPerM;

    const dailyCost = costPerRequest * requestsPerDay;
    const monthlyCost = dailyCost * 30;
    const yearlyCost = dailyCost * 365;

    // Token Cost Breakdown
    const inputCostShare = (inputTokens / 1_000_000) * currentModel.inputCostPerM * requestsPerDay;
    const outputCostShare = (outputTokens / 1_000_000) * currentModel.outputCostPerM * requestsPerDay;
    const totalShare = inputCostShare + outputCostShare;
    
    const inputPercentage = totalShare > 0 ? (inputCostShare / totalShare) * 100 : 0;
    const outputPercentage = totalShare > 0 ? (outputCostShare / totalShare) * 100 : 0;

    // Cross-model Comparison (compute monthly cost for all models under same inputs)
    const modelComparisons = pricingData.map(model => {
        const reqCost = (inputTokens / 1_000_000) * model.inputCostPerM + 
                         (outputTokens / 1_000_000) * model.outputCostPerM;
        const monthCost = reqCost * requestsPerDay * 30;
        return {
            name: model.name,
            provider: model.provider,
            monthlyCost: monthCost
        };
    }).sort((a, b) => a.monthlyCost - b.monthlyCost);

    const maxMonthlyCost = Math.max(...modelComparisons.map(m => m.monthlyCost));

    const faqs = [
        {
            question: "How do input and output token costs differ?",
            question_id: "cost-q1",
            answer: "Inference APIs charge significantly more for output tokens than input tokens (typically 4x to 5x higher). This is because generating tokens requires maintaining the model state sequentially, which is far more GPU-compute intensive than processing inputs in parallel."
        },
        {
            question: "What is context caching and how does it save costs?",
            question_id: "cost-q2",
            answer: "Providers like Google and DeepSeek offer context caching. If you reuse large static blocks of text (like system prompts or RAG context) across subsequent requests, you only pay a fraction of the cost (up to 90% cheaper) for cache-hits, drastically reducing token bills."
        },
        {
            question: "Why should I use a local LLM instead of APIs?",
            question_id: "cost-q3",
            answer: "If your system processes millions of requests a day, API costs grow linearly. Self-hosting open-weight models (like Llama 3) converts variable token costs into fixed hardware amortization expenses, which becomes highly profitable at massive query volumes."
        }
    ];

    const seoContent = (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            <h2>How LLM Pricing Schemes Work</h2>
            <p>
                Commercial LLM providers charge on a utility billing structure based on the quantity of <strong>million tokens processed (MTok)</strong>. This pricing is split into two components:
            </p>
            <ul>
                <li><strong>Input Tokens:</strong> Prompt tokens sent to the API, including system instructions, context retrievals, and history.</li>
                <li><strong>Output Tokens:</strong> Completion tokens generated by the LLM response.</li>
            </ul>

            <h3>Factors Affecting API Cost Scales</h3>
            <p>
                API pricing is heavily linked to model scale. Lightweight models (e.g., <strong>GPT-4o mini</strong> or <strong>Gemini 1.5 Flash</strong>) cost fractions of a cent per request and are ideal for high-frequency classification tasks. Large, highly reasoning frontier models (e.g., <strong>Claude 3.5 Sonnet</strong> or <strong>GPT-4o</strong>) cost up to 20x more but are required for multi-step reasoning, agent execution, and complex coding assignments.
            </p>

            <h3>How to Reduce API and Token Costs</h3>
            <p>
                Developers optimize costs by:
            </p>
            <ol style={{ paddingLeft: '1.5rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                <li><strong>Prompt Pruning:</strong> Removing boilerplate system roles and restricting instructions.</li>
                <li><strong>Dynamic Routing:</strong> Routing simple intents to mini models and reserving advanced reasoning for frontier models.</li>
                <li><strong>Cache Optimization:</strong> Structuring requests to take advantage of prompt cache-hits.</li>
                <li><strong>Output Truncation:</strong> Limiting max output tokens to prevent long conversational loops.</li>
            </ol>

            <h3>Internal Links</h3>
            <ul>
                <li><Link href="/ai-tools" style={{ color: "var(--accent-primary)", textDecoration: "underline" }}>AI Developer Ecosystem Hub</Link></li>
                <li><Link href="/ai-tools/ai-agent-cost-calculator" style={{ color: "var(--accent-primary)", textDecoration: "underline" }}>AI Agent Cost Calculator</Link></li>
                <li><Link href="/guides/how-llm-pricing-works" style={{ color: "var(--accent-primary)", textDecoration: "underline" }}>Deep Guide: How LLM Pricing Works</Link></li>
                <li><Link href="/guides/how-to-reduce-token-costs" style={{ color: "var(--accent-primary)", textDecoration: "underline" }}>Deep Guide: Reducing Token Costs</Link></li>
            </ul>
        </div>
    );

    return (
        <AIToolLayout
            title="LLM API Cost Calculator"
            description="Estimate LLM API cost projections. Select models and volume parameters to calculate cost per request, day, month, and year."
            slug="llm-cost-calculator"
            faqs={faqs}
            seoContent={seoContent}
        >
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))", gap: "2rem", marginBottom: "3rem" }}>
                {/* Inputs card */}
                <div className="card" style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
                    <div className="input-group">
                        <label className="input-label">Select LLM Model</label>
                        <select 
                            value={modelSlug} 
                            onChange={(e) => setModelSlug(e.target.value)}
                            className="input-field"
                        >
                            {pricingData.map(model => (
                                <option key={model.slug} value={model.slug}>
                                    {model.provider} - {model.name}
                                </option>
                            ))}
                        </select>
                    </div>

                    <div className="input-group">
                        <label className="input-label" style={{ display: "flex", justifyContent: "space-between" }}>
                            <span>Prompt (Input) Tokens</span>
                            <span style={{ color: "var(--accent-primary)", fontFamily: "var(--font-mono)" }}>
                                {inputTokens.toLocaleString()}
                            </span>
                        </label>
                        <input 
                            type="range" 
                            min="100" 
                            max="30000" 
                            step="100" 
                            value={inputTokens} 
                            onChange={(e) => setInputTokens(Number(e.target.value))} 
                        />
                        <input 
                            type="number" 
                            className="input-field" 
                            style={{ marginTop: "0.5rem", padding: "0.5rem" }}
                            value={inputTokens} 
                            onChange={(e) => setInputTokens(Math.max(0, Number(e.target.value)))}
                        />
                    </div>

                    <div className="input-group">
                        <label className="input-label" style={{ display: "flex", justifyContent: "space-between" }}>
                            <span>Completion (Output) Tokens</span>
                            <span style={{ color: "var(--accent-primary)", fontFamily: "var(--font-mono)" }}>
                                {outputTokens.toLocaleString()}
                            </span>
                        </label>
                        <input 
                            type="range" 
                            min="50" 
                            max="8000" 
                            step="50" 
                            value={outputTokens} 
                            onChange={(e) => setOutputTokens(Number(e.target.value))} 
                        />
                        <input 
                            type="number" 
                            className="input-field" 
                            style={{ marginTop: "0.5rem", padding: "0.5rem" }}
                            value={outputTokens} 
                            onChange={(e) => setOutputTokens(Math.max(0, Number(e.target.value)))}
                        />
                    </div>

                    <div className="input-group">
                        <label className="input-label" style={{ display: "flex", justifyContent: "space-between" }}>
                            <span>API Requests / Day</span>
                            <span style={{ color: "var(--accent-primary)", fontFamily: "var(--font-mono)" }}>
                                {requestsPerDay.toLocaleString()}
                            </span>
                        </label>
                        <input 
                            type="range" 
                            min="10" 
                            max="50000" 
                            step="10" 
                            value={requestsPerDay} 
                            onChange={(e) => setRequestsPerDay(Number(e.target.value))} 
                        />
                        <input 
                            type="number" 
                            className="input-field" 
                            style={{ marginTop: "0.5rem", padding: "0.5rem" }}
                            value={requestsPerDay} 
                            onChange={(e) => setRequestsPerDay(Math.max(0, Number(e.target.value)))}
                        />
                    </div>
                </div>

                {/* Outputs & Visualizations Card */}
                <div className="card" style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
                    <h3 className="input-label">Projected Expenses</h3>

                    {/* Cost cards */}
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
                        <div style={{ padding: "1.25rem", backgroundColor: "var(--bg-tertiary)", borderRadius: "var(--radius-sm)", border: "1px solid var(--border-color)" }}>
                            <div style={{ fontSize: "0.75rem", color: "var(--text-secondary)", textTransform: "uppercase" }}>Cost / Request</div>
                            <div style={{ fontSize: "1.5rem", color: "var(--accent-primary)", fontFamily: "var(--font-mono)", fontWeight: "bold" }}>
                                ${costPerRequest === 0 ? "0.00" : costPerRequest < 0.0001 ? "< $0.0001" : costPerRequest.toFixed(5)}
                            </div>
                        </div>
                        <div style={{ padding: "1.25rem", backgroundColor: "var(--bg-tertiary)", borderRadius: "var(--radius-sm)", border: "1px solid var(--border-color)" }}>
                            <div style={{ fontSize: "0.75rem", color: "var(--text-secondary)", textTransform: "uppercase" }}>Daily Cost</div>
                            <div style={{ fontSize: "1.5rem", color: "var(--text-primary)", fontFamily: "var(--font-mono)", fontWeight: "bold" }}>
                                ${dailyCost.toFixed(2)}
                            </div>
                        </div>
                    </div>

                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
                        <div style={{ padding: "1.25rem", backgroundColor: "var(--bg-tertiary)", borderRadius: "var(--radius-sm)", border: "1px solid var(--border-color)" }}>
                            <div style={{ fontSize: "0.75rem", color: "var(--text-secondary)", textTransform: "uppercase" }}>Monthly Cost</div>
                            <div style={{ fontSize: "1.5rem", color: "var(--text-primary)", fontFamily: "var(--font-mono)", fontWeight: "bold" }}>
                                ${monthlyCost.toFixed(2)}
                            </div>
                        </div>
                        <div style={{ padding: "1.25rem", backgroundColor: "var(--bg-tertiary)", borderRadius: "var(--radius-sm)", border: "1px solid var(--border-color)" }}>
                            <div style={{ fontSize: "0.75rem", color: "var(--text-secondary)", textTransform: "uppercase" }}>Yearly Cost</div>
                            <div style={{ fontSize: "1.5rem", color: "var(--text-primary)", fontFamily: "var(--font-mono)", fontWeight: "bold" }}>
                                ${yearlyCost.toFixed(2)}
                            </div>
                        </div>
                    </div>

                    {/* Cost Breakdown Progress Bar */}
                    <div style={{ marginTop: "1rem" }}>
                        <div style={{ display: "flex", justifyContent: "space-between", fontSize: "0.75rem", color: "var(--text-secondary)", textTransform: "uppercase", marginBottom: "0.5rem" }}>
                            <span>Prompt ({inputPercentage.toFixed(0)}%)</span>
                            <span>Completion ({outputPercentage.toFixed(0)}%)</span>
                        </div>
                        <div className="score-bar" style={{ height: "12px" }}>
                            <div style={{ display: "flex", height: "100%" }}>
                                <div style={{ width: `${inputPercentage}%`, backgroundColor: "var(--accent-primary)", transition: "width 0.3s" }} />
                                <div style={{ width: `${outputPercentage}%`, backgroundColor: "#06B6D4", transition: "width 0.3s" }} /> {/* Cyan */}
                            </div>
                        </div>
                        <div style={{ display: "flex", justifyContent: "space-between", fontSize: "0.8rem", color: "var(--text-secondary)", marginTop: "0.5rem" }}>
                            <span>${inputCostShare.toFixed(2)} / Day</span>
                            <span>${outputCostShare.toFixed(2)} / Day</span>
                        </div>
                    </div>
                </div>
            </div>

            {/* Model Comparison Chart */}
            <div className="card" style={{ marginBottom: "3rem" }}>
                <h3 style={{ fontSize: "1.5rem", marginBottom: "1.5rem", borderBottom: "1px solid var(--border-color)", paddingBottom: "0.5rem" }}>
                    Monthly Cost Comparison Across Models
                </h3>
                <p style={{ color: "var(--text-secondary)", fontSize: "0.9rem", marginBottom: "1.5rem" }}>
                    Compare what it would cost to run your configured volume of {requestsPerDay.toLocaleString()} requests/day ({inputTokens.toLocaleString()} in / {outputTokens.toLocaleString()} out) across other models.
                </p>

                <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
                    {modelComparisons.map((item, i) => {
                        const widthPercentage = maxMonthlyCost > 0 ? (item.monthlyCost / maxMonthlyCost) * 100 : 0;
                        const isSelected = item.name === currentModel.name && item.provider === currentModel.provider;

                        return (
                            <div key={i} style={{ display: "flex", flexDirection: "column", gap: "0.25rem" }}>
                                <div style={{ display: "flex", justifyContent: "space-between", fontSize: "0.875rem" }}>
                                    <span style={{ fontWeight: isSelected ? "bold" : "normal", color: isSelected ? "var(--accent-primary)" : "var(--text-primary)" }}>
                                        {item.provider} - {item.name} {isSelected && " (Selected)"}
                                    </span>
                                    <span style={{ fontFamily: "var(--font-mono)", fontWeight: "bold" }}>
                                        ${item.monthlyCost.toFixed(2)}/mo
                                    </span>
                                </div>
                                <div style={{ height: "24px", backgroundColor: "var(--bg-tertiary)", borderRadius: "var(--radius-sm)", overflow: "hidden", border: isSelected ? "1px solid var(--accent-primary)" : "1px solid transparent" }}>
                                    <div style={{ 
                                        width: `${Math.max(1, widthPercentage)}%`, 
                                        height: "100%", 
                                        backgroundColor: isSelected ? "var(--accent-primary)" : "var(--bg-surface)",
                                        opacity: isSelected ? 1 : 0.6,
                                        transition: "width 0.3s ease" 
                                    }} />
                                </div>
                            </div>
                        );
                    })}
                </div>
            </div>
        </AIToolLayout>
    );
}
