"use client";

import { useState, useEffect, useRef } from "react";
import ToolLayout from "@/components/ToolLayout";
import Link from "next/link";
import { trackUsage } from "@/lib/tracker";
import CurrencySelector from "@/components/CurrencySelector";
import { CurrencyCode, CURRENCY_RATES, formatCurrency } from "@/lib/currencyRates";

export default function CACPaybackCalculator() {
    const [cac, setCac] = useState<number>(500);
    const [arpu, setArpu] = useState<number>(50);
    const [margin, setMargin] = useState<number>(80);

    const [currency, setCurrency] = useState<CurrencyCode>("USD");
    const tracked = useRef(false);

    useEffect(() => {
        const saved = localStorage.getItem("tool_currency") as CurrencyCode;
        if (saved && CURRENCY_RATES[saved]) {
            setCurrency(saved);
        }
        if (!tracked.current) {
            trackUsage("cac-payback-calculator");
            tracked.current = true;
        }
    }, []);

    const handleCurrencyChange = (c: CurrencyCode) => {
        setCurrency(c);
        localStorage.setItem("tool_currency", c);
    };

    const rate = CURRENCY_RATES[currency].rate;
    const symbol = CURRENCY_RATES[currency].symbol;

    const monthlyGrossProfit = arpu * (margin / 100);
    const paybackMonths = monthlyGrossProfit > 0 ? cac / monthlyGrossProfit : Infinity;

    let scoreStatus = "Excellent";
    let scoreColor = "var(--success-color, #22c55e)";

    if (paybackMonths > 18) {
        scoreStatus = "Danger";
        scoreColor = "var(--error-color, #ef4444)";
    } else if (paybackMonths > 12) {
        scoreStatus = "Warning";
        scoreColor = "var(--accent-muted)";
    } else if (paybackMonths > 6) {
        scoreStatus = "Good";
        scoreColor = "var(--accent-primary)";
    }

    const resetValues = () => {
        setCac(500 / rate);
        setArpu(50 / rate);
        setMargin(80);
    };

    const faqs = [
        { question: "What is CAC Payback Period?", answer: "CAC Payback Period is the number of months it takes for a company to earn back the Customer Acquisition Cost (CAC) through the gross profit generated by that customer." },
        { question: "What is a good CAC payback period?", answer: "For SMB SaaS, 12 months is standard. For enterprise SaaS, 18-24 months is acceptable. Anything under 6 months is exceptional." },
        { question: "Why include gross margin in the calculation?", answer: "Revenue isn't profit. If it costs you money to deliver your service (hosting, support), those costs must be subtracted from revenue to see how much real cash is paying back the acquisition cost." }
    ];

    const jsonLd = {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": "CAC Payback Period Calculator",
        "applicationCategory": "BusinessApplication",
        "offers": { "@type": "Offer", "price": "0" },
        "description": "Calculate your CAC payback period and assess the capital efficiency of your business."
    };

    const seoContent = (
        <>
            <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
            <h2>Understanding CAC Payback Period for SaaS</h2>
            <p>Customer Acquisition Cost (CAC) payback period is one of the most critical capital efficiency metrics. It answers a simple question: How long does your cash stay tied up in a customer before you break even on marketing and sales spend?</p>
            <h3>Why Months to Recover CAC Matters</h3>
            <p>If your payback period is 6 months, you can reinvest the same dollar twice in a single year. If your payback period is 24 months, your growth depends heavily on external funding to float cash burn.</p>
            <h3>Relevant Links</h3>
            <ul>
                <li><Link href="/">Homepage</Link></li>
                <li><Link href="/tools/customer-lifetime-value-calculator">Customer Lifetime Value Calculator</Link></li>
                <li><Link href="/tools/startup-burn-rate-calculator">Startup Burn Rate Calculator</Link></li>
            </ul>
        </>
    );

    const formatNumber = (num: number) => {
        return new Intl.NumberFormat('en-US', { maximumFractionDigits: 1 }).format(num);
    };

    return (
        <ToolLayout
            title="CAC Payback Period Calculator"
            description="Calculate your CAC payback period and assess the capital efficiency of your business."
            slug="cac-payback-calculator"
            faqs={faqs}
            seoContent={seoContent}
        >
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: "2rem" }}>
                <div className="card stagger-1" style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                        <h3 style={{ fontSize: "1.25rem", color: "var(--text-primary)" }}>Inputs</h3>
                        <button onClick={resetValues} className="pill" style={{ cursor: "pointer", background: "var(--bg-secondary)", border: "1px solid var(--border-color)", color: "var(--text-secondary)" }}>
                            Reset
                        </button>
                    </div>

                    <CurrencySelector currency={currency} onChange={handleCurrencyChange} />

                    <div className="input-group">
                        <label className="input-label">Customer Acquisition Cost ({symbol})</label>
                        <input type="number" className="input-field" value={cac ? Number((cac * rate).toFixed(2)) : 0} onChange={(e) => setCac((Number(e.target.value) || 0) / rate)} />
                    </div>

                    <div className="input-group">
                        <label className="input-label">Monthly Revenue per User ({symbol})</label>
                        <input type="number" className="input-field" value={arpu ? Number((arpu * rate).toFixed(2)) : 0} onChange={(e) => setArpu((Number(e.target.value) || 0) / rate)} />
                    </div>

                    <div className="input-group">
                        <label className="input-label" style={{ display: "flex", justifyContent: "space-between" }}>
                            <span>Gross Margin %</span>
                            <span style={{ color: "var(--accent-primary)", fontFamily: "var(--font-mono)" }}>{margin}%</span>
                        </label>
                        <input type="range" min="1" max="100" step="1" value={margin} onChange={(e) => setMargin(Number(e.target.value))} />
                    </div>
                </div>

                <div className="card stagger-2" style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
                    <div style={{ padding: "1.5rem", backgroundColor: "var(--bg-tertiary)", borderRadius: "var(--radius-sm)", border: "1px solid var(--accent-primary)", textAlign: "center" }}>
                        <div className="input-label" style={{ color: "var(--accent-primary)", marginBottom: "0.5rem" }}>Payback Period</div>
                        <div style={{ fontSize: "3rem", color: "var(--text-primary)", fontFamily: "var(--font-mono)", fontWeight: "bold", lineHeight: 1 }}>
                            {paybackMonths === Infinity ? "Never" : `${formatNumber(paybackMonths)}`} <span style={{ fontSize: "1rem", color: "var(--text-secondary)" }}>months</span>
                        </div>
                    </div>

                    <div style={{ padding: "1.5rem", borderLeft: `4px solid ${scoreColor}`, backgroundColor: "var(--bg-tertiary)", borderRadius: "0 var(--radius-sm) var(--radius-sm) 0" }}>
                        <div className="input-label" style={{ marginBottom: "0.5rem" }}>CAC Efficiency Score</div>
                        <div style={{ fontSize: "1.25rem", color: scoreColor, fontWeight: "bold" }}>{scoreStatus}</div>
                    </div>
                </div>
            </div>
        </ToolLayout>
    );
}
